### ISSUE TITLE
max-tick-time

### ISSUE THREAD

**Issue by kenijey** [jaideepheer/MinecraftForge-Mods-ServerPropertiesLAN#3]
max-tick-time
please add it... thank you...
i need to set it to -1.

**Comment by jaideepheer** [comment]
Why -1. That would just give you normal vanilla behavior.

**Comment by kenijey** [comment]
cus my lan server kicks my friend because of her latency. she has a slow internet and till her client downloads the world, server kicks her. u know a better solution?

**Comment by jaideepheer** [comment]
Well, maxticktime can't solve this problem. It's probably caused due to a network timeout. I'll need both your and your friend's log to help in this.

**Comment by kenijey** [comment]
uhm, [here is](https://github.com/kenijey/Ezteria) my modpack. if she has bad internet connection, my server kicks her after about 30 seconds. sometimes, if she makes the render distance to 2(me too) she can conect then play. we could play also in vanilla. 
i will send logs when we try to play it again(probably tomorrow or this night today) thanks again.

**Comment by jaideepheer** [comment]
I couldn't add maxticktime support though.
Closing this issue now, please make a new issue as a feature request, for the configurable network timeout.
