### ISSUE TITLE
Repost request

### ISSUE THREAD

**Issue by Mycrafte** [jaideepheer/MinecraftForge-Mods-ServerPropertiesLAN#6]
I am a player who came from china,and i love ur mod very much!
Its easy for me to download ur lovely mod  cuz i have VPN,but because of the GFW,most of us cannot download ur mod or visit curseforge.
So i find a new way to "rescue" them!
This is a website [www.mcmod.cn]created by chinese Minecrafter, its a chinese ModWiki,I want to repost ur mod to this website.
Of course,i will mention ur name and url,we wont use this mod to earn any money,wo will keep ur mod original.
Hope you can agree!

**Comment by jaideepheer** [comment]
Approved. 👍

**Comment by Mycrafte** [comment]
Thanks!I will try my best to do it.




------------------ 原始邮件 ------------------
发件人: "Jaideep Singh Heer"<notifications@github.com>;
发送时间: 2018年6月15日(星期五) 晚上9:20
收件人: "jaideepheer/MinecraftForge-Mods-ServerPropertiesLAN"<MinecraftForge-Mods-ServerPropertiesLAN@noreply.github.com>;
抄送: "SinadCa"<keeptpa@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [jaideepheer/MinecraftForge-Mods-ServerPropertiesLAN] Repostrequest (#6)




Approved.
